spring:
  profiles:
    active: ${PROFILE:local}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG